### ISSUE TITLE
error in search blast results

### ISSUE THREAD

**Issue by mblaxter** [mojones/AfterParty2#1]
http://afterparty.bio.ed.ac.uk/compoundSample/show/666146

initially i was getting 

Grails Runtime Exception

Error Details

Error 500: Executing action [searchContigSets] of controller
[afterparty.ContigSetController] caused exception: Runtime error executing
action
Servlet: grails
URI: /grails/contigSet/searchContigSets.dispatch
Exception Message: Cannot invoke method toInteger() on null object
Caused by: Cannot invoke method toInteger() on null object
Class: GrailsFragmentCachingFilter
At Line: [66]
Code Snippet:

Stack Trace

java.lang.NullPointerException: Cannot invoke method toInteger() on null
object

```
at
```

afterparty.ContigSetController$_closure11.doCall(ContigSetController.groovy:299)

```
at
```

grails.plugin.springcache.web.GrailsFragmentCachingFilter.doFilter(GrailsFragmentCachingFilter.groovy:66)

```
at net.sf.ehcache.constructs.web.filter.Filter.doFilter(Filter.java:86)

at
```

com.linkedin.grails.profiler.ProfilerFilter.doFilterInternal(ProfilerFilter.java:82)

```
at
```

java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)

```
at
```

java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)

```
at java.lang.Thread.run(Thread.java:679)
```

but now I am getting no response at all (or being bounced back to the page I started from - hard to tell)

Firefox 12.0, MacOS X 10.6.8, two finger typist

**Comment by mojones** [comment]
probably fixed as a side-effect of other fixes; please re-open if not.
