### ISSUE TITLE
look and feel suggestions from MLB

### ISSUE THREAD

**Issue by mblaxter** [mojones/AfterParty2#24]
general comment on [contig|contig set] view:
would be good to have a breadcrumb of the name of the species/dataset etc to contextualise each one

report formatting
would be good to have more measured formatting of dataset intro pages (ie at present it appears that the fact that the dataset HAS a name is more important than the name)

blast searching
permit setting of parameters on blast searches
state parameters used in blast search defaults

blast reports
tabulating blast reporting on contig overview/set page to separate out E-value and bit score into columns

**Comment by mojones** [comment]
I have split these into separate action items, closing this one.
