### ISSUE TITLE
linkout to Uniprot misformed

### ISSUE THREAD

**Issue by mblaxter** [mojones/AfterParty2#3]
http://afterparty.bio.ed.ac.uk/contig/show/712146
[but any contig will do]

the linkouts to uniprot give  misformed queries at ENA

http://www.uniprot.org/uniprot/UniRef100_P49672

404 Not Found

The resource you requested could not be found. It has either been moved, never existed, or you might have mistyped the address.

```
If you believe this is an error or need further help please contact us.
You can also start navigating from the main page.
You can also try using the search functionality above.
```

**Comment by mojones** [comment]
fixed - it was caused by NemBase storing uniprot accession numbers prepended with UniRef100_
