### ISSUE TITLE
feature creep - breadcrumbs

### ISSUE THREAD

**Issue by mblaxter** [mojones/AfterParty2#4]
see eg http://afterparty.bio.ed.ac.uk/contig/show/709903

which species/assembly/ etc is this from, and which contig is it?

It is diffcult to navigate BACK to the last page visited to revisit questions asked or gene lists... 

Contig pages shopuld have their "containers" linked in (assembly, species, etc) as a minimum

question is how to enable this... i am guessing breadcrumbs would be harsh, but perhaps each dataset contig page could have a link to its home (assembly) page and each assembly to its (species) etc..,

**Comment by mojones** [comment]
one
